projects:
  Codegen Project:
    schemaPath: schema.json
    includes:
      - src/graphql/**/*.js
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: src/graphql
        region: ap-northeast-1
        apiId: e4s7thvgube57p2uhm6t6tiyjy
        frontend: javascript
        framework: react
        maxDepth: 2
extensions:
  amplify:
    version: 3
