// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const config = {
  Auth: {
    Cognito: {
      userPoolId: "ap-northeast-1_ncffAodBj",
      userPoolClientId: "5buno8gs9brj93apmu9tvqqp77",
      region: "ap-northeast-1",
      loginWith: {
        oauth: {
          domain: "ap-northeast-1ncffaodbj.auth.ap-northeast-1.amazoncognito.com",
          scopes: ["openid", "email"],
          redirectSignIn: ["https://main.d3rgq9lalaa9gb.amplifyapp.com"],
          redirectSignOut: ["https://main.d3rgq9lalaa9gb.amplifyapp.com"],
          responseType: "code"
        }
      }
    }
  },
    API: {
        GraphQL: {
          endpoint: 'https://lnbqw6f7avh7ze3szmlszlhrzy.appsync-api.ap-northeast-1.amazonaws.com/graphql',
          region: 'ap-northeast-1',
          defaultAuthMode: 'apiKey',
          apiKey: 'da2-wkiiwoa5wbhflhvsx3m5qr7mxq'
        },
    }
};

export default config;