// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.


// const config =  {
//   aws_project_region: 'ap-northeast-1',
//   aws_appsync_graphqlEndpoint: 'https://qnem7fbxyqxacvnz4yvxkqem.appsync-api.ap-northeast-1.amazonaws.com/graphql',
//   aws_appsync_region: 'ap-northeast-1',
//   aws_appsync_authenticationType: 'AMAZON_COGNITO_USER_POOLS',
//     API: {
//         GraphQL: {
//           endpoint: 'https://gneum7fbxvggxacvnz4yvxkqem.appsync-api.ap-northeast-1.amazonaws.com/graphql',
//           region: 'ap-northeast-1',
//           defaultAuthMode: 'userPool',
//         }
//     }
// };

// export default config;

const config = {
  // ベース設定
  aws_project_region: 'ap-northeast-1',
  
  // AppSync設定（正しいエンドポイント）
  aws_appsync_graphqlEndpoint: 'https://gneum7fbxvggxacvnz4yvxkqem.appsync-api.ap-northeast-1.amazonaws.com/graphql',
  aws_appsync_region: 'ap-northeast-1',
  aws_appsync_authenticationType: 'AMAZON_COGNITO_USER_POOLS',
  
  // Cognito設定（必須追加）
  aws_cognito_region: 'ap-northeast-1',
  aws_user_pools_id: 'ap-northeast-1_u9YhtfyWO',
  aws_user_pools_web_client_id: '8pua3oe15pci4ci7m0misd8eu',
  
  // Amplify v6 API設定（正しいエンドポイント）
  API: {
    GraphQL: {
      endpoint: 'https://gneum7fbxvggxacvnz4yvxkqem.appsync-api.ap-northeast-1.amazonaws.com/graphql',
      region: 'ap-northeast-1',
      defaultAuthMode: 'userPool',
    }
  },
  
  // Auth設定（v6対応）
  Auth: {
    region: 'ap-northeast-1',
    userPoolId: 'ap-northeast-1_u9YhtfyWO',
    userPoolWebClientId: '8pua3oe15pci4ci7m0misd8eu',
    
    // OIDC連携設定
    oauth: {
      domain: 'ap-northeast-1u9yhtfywo.auth.ap-northeast-1.amazoncognito.com',
      scope: ['email', 'openid', 'profile', 'aws.cognito.signin.user.admin'],
      redirectSignIn: 'https://main.d3rgq9lalaa9gb.amplifyapp.com/',
      redirectSignOut: 'https://main.d3rgq9lalaa9gb.amplifyapp.com/',
      responseType: 'code',
    }
  }
};

export default config;